ADAPT-2102 Add Hero component
SU-SWS/decanter-react pull request #56
Opened 2021-08-03 15:51 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- Add Hero component

# Needed By (Date)
- tbd

# Urgency
- low

# Steps to Test

1. Do this
1. Then this
2. Then this

# Associated Issues and/or People
- [ADAPT-2102](https://stanfordits.atlassian.net/browse/ADAPT-2102)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-08-03 18:11 UTC, rebeccahongsf commented
Decanter v6 Hero contains [custom heights](https://github.com/SU-SWS/decanter/blob/v6/core/src/scss/components/hero/_hero.scss#L3-L11) at specific breakpoints. I've current set it to `su-max-h-500` (i.e. max-height: 50rem).

Is this something we should incorporate within our [maxHeight file](https://github.com/SU-SWS/decanter/blob/v7/src/plugins/theme/maxHeight.js) in Decanter v7? 🤔

2021-08-03 18:34 UTC, yvonnetangsu commented
> Decanter v6 Hero contains [custom heights](https://github.com/SU-SWS/decanter/blob/v6/core/src/scss/components/hero/_hero.scss#L3-L11) at specific breakpoints. I've current set it to `su-max-h-500` (i.e. max-height: 50rem).
> 
> Is this something we should incorporate within our [maxHeight file](https://github.com/SU-SWS/decanter/blob/v7/src/plugins/theme/maxHeight.js) in Decanter v7? 🤔

Oh interesting....those are very specific max heights. Hmmmm let's go with the closest value for now, since we aren't going for an exact 1:1 match with Decanter 6 currently. If we absolutely need those values later, we can always add them 😄

2021-08-17 06:00 UTC, sherakama commented on src/Hero/Hero.js
> +  bgImage: { src } = {},
If you are not using any other values than src why make this parameter an object?

2021-08-17 06:02 UTC, sherakama approved these changes
Other than my one question about the bgImage prop being an object vs a string this is looking great and is gtg.

2021-08-17 16:15 UTC, yvonnetangsu commented
This looks great! I was thinking though, the one with the caption seems like it belongs in a different family. I think we're going to need a component with image and caption (kind of like the CaptionMedia component we have on SAA). Think we could move the Hero with the small caption into a a different component, then we could add other options later (eg, caption alignment) 😄

2021-09-02 08:47 UTC, yvonnetangsu requested changes
Sorry for taking so long to get back to this! 

1. Looks like currently it might breakdown for mobile if the text gets long. Please see if you could make the image height expand to accommodate the amount of text 😄  
![Screen Shot 2021-09-02 at 1 48 48 AM](https://user-images.githubusercontent.com/42749717/131813417-8f0b05ad-0697-4058-8b0b-caf4e1404441.png)

2. We could probably use larger font sizes for the description and maybe even the superheadline. I suggest talking to Kerri (since she's the design gatekeeper of Decanter) to see if she has font size suggestions.

Looking great! Thank you for the work 🙏🏼

2021-09-20 17:12 UTC, rebeccahongsf commented
Mini Update: 
1. Text issue for the Custom Gradient with text overlay should now be resolved for mobile:
![image](https://user-images.githubusercontent.com/34019925/134044724-4620a14f-a7e1-4a5f-87f3-03b9f0d2fbc4.png)

2. Checked in with Kerri — will update PR with rec font-sizes once I hear back!

2021-09-21 16:28 UTC, yvonnetangsu commented
Yay - thank you for the revision, @rebeccahongsf ! ❤️

2021-09-21 18:51 UTC, rebeccahongsf commented
I think we're ready for another round of reviews @yvonnetangsu :D Thank you for your patience and feedback!

2021-09-21 18:59 UTC, yvonnetangsu commented
@rebeccahongsf Looks like default hero mobile view got a little chopped off on mobile at the bottom 😄 
![Screen Shot 2021-09-21 at 11 59 06 AM](https://user-images.githubusercontent.com/42749717/134231418-5cc1cbc7-a69f-44e8-b44c-6f480d0644b0.png)

2021-09-21 19:30 UTC, rebeccahongsf commented
@yvonnetangsu, now it should be g2g. Thanks again!

2021-09-21 19:51 UTC, yvonnetangsu commented
@rebeccahongsf One more 😄 
I would probably take away the max height on that 2nd variant:
Currently with max height 500:
![Screen Shot 2021-09-21 at 12 49 42 PM](https://user-images.githubusercontent.com/42749717/134238179-a1524c73-849f-485a-acdf-0970beb09dde.png)

After
![Screen Shot 2021-09-21 at 12 49 58 PM](https://user-images.githubusercontent.com/42749717/134238226-c97918bf-18ad-476d-817d-308167cad15e.png)
:

2021-09-22 20:53 UTC, merged