ADAPT-3762 Add icon button alignment options
SU-SWS/decanter-react pull request #82
Opened 2021-10-07 16:10 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Add icon alignment/position options to Buttons, Cta Buttons, and Cta Links.
- Add X and Upload Icons.
- Add Up icon animation

# Needed By (Date)
- tbd

# Urgency
- medium

# Steps to Test

1. Pull this PR and review locally or on Netlify
-  Button: `/story/simple-button--email` || [Netlify](https://deploy-preview-82--decanter-react.netlify.app/?path=/story/simple-button--email)
- Cta Button: `/story/simple-cta-link-button--action` || [Netlify](https://deploy-preview-82--decanter-react.netlify.app/?path=/story/simple-cta-link-button--action)
- Cta Link: `/story/simple-cta-link--email&args=iconPosition:left` || [Netlify](https://deploy-preview-82--decanter-react.netlify.app/?path=/story/simple-cta-link--email&args=iconPosition:left)

2. Check to see that the icons properly align left and right.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [ADAPT-3762](https://stanfordits.atlassian.net/browse/ADAPT-3762)
- [ADAPT-3820](https://stanfordits.atlassian.net/browse/ADAPT-3820)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-10-08 19:19 UTC, yvonnetangsu commented on src/Button/Button.js
> +        ) : null}
Is it possible to place the children inside the conditional render blocks instead of the HeroIcon? That way there's a bit less duplicate code 😄

2021-10-08 19:21 UTC, yvonnetangsu commented on src/Button/Button.js
> +        ) : null}
Same for the other 2 components ^^^

2021-10-08 19:22 UTC, yvonnetangsu requested changes
Just a couple questions about placing the children inside the conditionals instead of the HeroIcon and Storyblok UI. After that GTG for me. Thanks, @rebeccahongsf ! 😄

2021-10-12 00:14 UTC, yvonnetangsu commented on src/Button/Button.js
> +        {iconPosition === 'right' ? <>{children}</> : null}
Is there a reason children needs the fragment wrapper? Could we lose them so just 
{iconPosition === 'right' ? children : null}? 😄

2021-10-20 20:40 UTC, sherakama commented
This is now on hold. Please wait until further notice to where this work is going.

2021-12-08 15:48 UTC, rebeccahongsf commented
PR clean up! — Closing out since this is no longer needed.

2021-12-08 15:48 UTC, closed without merging